[package]
name = "example-themed-counter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bubbletea.workspace = true
lipgloss.workspace = true
anyhow.workspace = true
