[package]
name = "example-viewport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "viewport"
path = "src/main.rs"

[dependencies]
bubbletea.workspace = true
bubbles.workspace = true
lipgloss.workspace = true
anyhow.workspace = true
